# Generated by Django 5.2.6 on 2025-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
