# Generated by Django 5.2.6 on 2025-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_comunidad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
