# Generated by Django 5.2.6 on 2025-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_alter_comunidad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/'),
        ),
    ]
