# Generated by Django 5.2.6 on 2025-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_comunidad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
