# Generated by Django 5.2.6 on 2025-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='plantel',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
