# Generated by Django 5.2.6 on 2025-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_alter_escuela_nombre_alter_escuela_plantel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
