# Generated by Django 5.2.6 on 2025-09-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='semestre',
        ),
    ]
