# Generated by Django 5.2.6 on 2025-09-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('comunidades', '0001_initial'),
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad'),
        ),
    ]
