# Generated by Django 5.2.6 on 2025-10-16 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0002_asignatura_categoria'),
        ('categorias', '0001_initial'),
        ('escuelas', '0003_escuela_slug'),
        ('maestros', '0002_remove_maestro_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.maestro')),
            ],
        ),
    ]
