# Generated by Django 5.2.8 on 2025-11-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_comunidad_alumno_especialidad'),
        ('asesorias', '0002_alter_asesoria_fecha'),
        ('escuelas', '0003_escuela_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='cupo',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela'),
        ),
        migrations.CreateModel(
            name='InscripcionAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesorias.asesoria')),
            ],
            options={
                'unique_together': {('alumno', 'asesoria')},
            },
        ),
    ]
