# Generated by Django 5.2.8 on 2025-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_comunidad_alumno_especialidad'),
        ('asesorias', '0003_asesoria_cupo_alter_asesoria_escuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='inscritos',
            field=models.ManyToManyField(blank=True, to='alumnos.alumno'),
        ),
    ]
