# Generated by Django 5.2.8 on 2025-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0004_asesoria_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionasesoria',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
